FROM debian:stable

RUN apt-get update && apt-get install -y --no-install-recommends python-pip
RUN apt-get install  -y  python-setuptools
RUN pip install requests
RUN pip install httmock
RUN pip install coverage
